*Computación científica 2*

Guía 1:
- Como se trabajará durante el curso
- Usar un notebook de forma ordenada
- NumPy
- Crear y manipular arreglos con NumPy:
Tamaño, forma, selección de datos y operaciones
- Hacer operaciones sin ciclos largos dado que Numpy trabaja por bloques


Semanas 1 - 8: Ciencia de datos (Pandas y SciPy)
Semanas 9 - 16: redes neuronales (Keras)

Metodología:
1. idea corta
2. ejemplo del profe en el notebook
3. ejercicios guiados y reto

**Lo importante es: qué se hizo, porqué y qué significado tiene el código**

Un notebook permite, probar ideas fácilmente, mostrar resultados y gráficas, dejar evidencia del trabajo (se guarda para tareas o proyectos)y se puede utilizar desde cualquier dispositivo.

Un notebook se ejecuta de arriba hacia abajo.
Cada bloque contiene una idea, es bueno comentar cada línea y si hay alguna función tomada de internet comentar el funcionamiento para **escalar el diseño**.

Verificar que el notebook quedó guardado y si hay algún error, lee el mensaje de error.


**NumPy**
Librería utilizada para trabajar con arreglos numéricos llamados **arrays**, es parecido a una lista pero pensado para hacer cálculos de manera eficiente y clara..

De esta manera NumPy es importante porque:
- En ciencia de datos muchas operaciones son sobre columnas
- En redes neuronales los datos se representan como arreglos
- NumPy permite escribir menos código y con menos errores

La diferencia entre array y lista es que array está enfocado en números para realizar operaciones rápidas, una lista puede incluir texto


**Shape (a.shape):** Si es un vector me dice el número de elementos x (x,) , si es una matriz el número de filas m y columnas n (m,n).

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3],
[4, 5, 6]])
print(a) # arreglo de 1 dimensión
print(b) # arreglo de 2 dimensiones (matriz)
print(a.shape) # (5,)
print(b.shape) # (2, 3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
(5,)
(2, 3)


**Selección de datos:**

 **indexación**
- a[n] selecciona el elemento n del array (index n), el primer elemento es el a[0], el último el a[-1], si es un vector el resultado es un numero o si es una matriz el resultado es un vector fila

**Slicing**
- a[i:k] selecciona desde el índice i hasta el k y el resultado es un vector o una serie de vectores fila
- a[m,n] Selecciona un solo elemento de la fila m, columna n.

In [24]:
a = np.array([10, 20, 30, 40, 50])
print(a[0]) # primer elemento (inicia en el cero)
print(a[-1]) # último elemento
print(a[-2]) # penúltimo elemento
print(a[1:4]) # desde el índice 1 hasta el 4 sin el 4 (hasta el 3)
print(a[0:5:2]) # desde el primero hasta el 4 de dos en dos [10, 30, 50]


b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b[0, 2]) # fila 0, columna 2
print(b[:, 1]) # todos los elementos (:) (todas las filas), columna 1
print(b[0]) # primer elemento (vector [1, 2, 3])
print(b[0, 0:2]) # primer vector, elementos del primero hasta el 2 sin el 2 (hasta el 1)
print(b[0:1, 0:2]) # vectores del 0 al 1 sin el 1, elementos del primero hasta el 2 sin el 2 (hasta el 1)
print(b[0:2, 0:2]) # vectores del 0 al 1, elementos de los vectores de la columna de la 0 a la 1
print(b[0:2]) # vectores fila, el primero y el segundo
print(b[:,0:2]) # Todas las filas (:), los elementos primero y segundo

#c=np.array([[10, 20], 5, 4]) porque no se puede hacer?
#print(c[0])
#print(c[1])

print(a[::-1])

10
50
40
[20 30 40]
[10 30 50]
3
[2 5]
[1 2 3]
[1 2]
[[1 2]]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[50 40 30 20 10]


**Operaciones directas**
Se permite hacer operaciones en bloque a cada array

In [33]:
x = np.array([1, 2, 3, 4])
print(x + 10) # suma 10 a cada elemento - [11 12 13 14]
print(x * 2) # multiplica cada elemento por 2 - [2 4 6 8]

y = np.array([10, 20, 30, 40])
print(x + y) # suma elemento a elemento - [11 22 33 44]
print(x * y) # multiplica elemento a elemento - [10 40 90 160]

# Modificación de solo algunos elementos
a=[0, 2, 3]
x[a]+=4 # se le suma 4 a los elementos escogidos con la lista a
print(x) # [5 2 7 8]

# Otras operaciones selectivas
a = np.array([10, 20, 30, 40, 50])
a[::2] *= 2       # [20, 20, 60, 40, 100]
a[:2] -= 5        # [15, 15, 60, 40, 100]
a[[1, 3]] **= 2   # [15, 225, 60, 1600, 100]
a[::-1]-=2        # [13 223 58 1598 98], si no se asigna a otra lista no cambia de sentido
print(a)

x = np.array([1, 2, 3, 4])
z=[0, 2, 3]
b=[1,2,3]
x[z]+=b # se le suma a cada elemento escogido con la lista z
        # un elemento respectivo de la lista b
print(x) # [2 2 5 7]

a = np.array([10, 20, 30, 40, 50])
a[::-1]+=2
b=a[::-1]  # ahora si b sería a al revés con la operación +2
print(b)

# raíz cuadrada , dtype=float
r = np.array([1, 4, 9, 16, 25])
r[2:]=np.sqrt(r[2:])
print(r) # [1 4 3 4 5] saca la raíz desde el elemento 2 en adelante

# indexación booleana (por condición)
c = np.array([10, -5, 20, -1, 30])
c[c < 0] = 0 # solo los elementos de c menores a cero se les reemplaza por cero
print(c) # [10 0 20 0 30]

# si la condición es una lógica muy específica se usar np.where()
t = np.array([1, 2, 3, 4, 5])

# "Si el número es mayor a 3, multiplícalo por 10; si no, déjalo igual"
d = np.where(t > 3, t * 10, t)

print(d) # [1, 2, 3, 40, 50]


[11 12 13 14]
[2 4 6 8]
[11 22 33 44]
[ 10  40  90 160]
[5 2 7 8]
[  13  223   58 1598   98]
[2 2 5 7]
[52 42 32 22 12]
[1 4 3 4 5]
[10  0 20  0 30]
[ 1  2  3 40 50]


**Promedios y medidas rápidas**

In [5]:
x = np.array([1, 2, 3, 4, 5])
print(np.mean(x)) # promedio
print(np.min(x)) # mínimo
print(np.max(x)) # máximo
print(np.sum(x)) # suma


3.0
1
5
15


**Broadcasting**

In [6]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([10, 20, 30])
print(M + v) # suma v a cada fila de M

[[11 22 33]
 [14 25 36]]


**respuestas a preguntas**
1. Un notebook es una mezcla entre texto y código, nos sirve para probar ideas de código fácilmente, dejarlas guardadas (lo que nos sirve para tareas y los proyectos) y poder manejar el código desde cualquier dispositivo.

2. Una lista puede contener texto, un array de NumPy es utilizado solo para números y realizar operaciones sobre ellos de manera eficaz y clara

3. shape significa forma y es una función que me dice de un array: si es un vector el numero de elementos x (x,), si es una matriz el numero de filas m y columnas n (m,n)

4. Debería devolverme [20, 30, 40], porque a[1:4] son los elementos del 1 al 3, prueba:

In [7]:
a=np.array([10, 20, 30, 40, 50])
print(a[1:4])

[20 30 40]


5. b.shape== (2,3) es distinto de b.shape = (2,3), el primero es una prueba de verdad, si la forma es igual a esa tupla entonces será verdadero, el segundo es una asignación que no se puede hacer porque la forma de b no puede cambiarse de esa manera, habría que cambiar como tal la matriz b, prueba:

In [8]:
b=np.array([[1, 2, 3],
            [4, 5, 6]]) #2x3

print(b.shape) # (2,3)
print(b.shape==(2,3)) # True
print(b.shape==(3,2)) # False
b.shape=(2,3) # asignación que no me dará ningún error
#b.shape=(2,4) # asignación que me dará error



(2, 3)
True
False


6. b[:,1] me devuelve todos los elementos de las filas (:), pero solo de la columna 1, técnicamente la segunda columna, ejemplo:

In [9]:
b=np.array([[1, 2, 3],
            [4, 5, 6]]) #2x3

print(b[:,1]) # Me dará de todas las filas (todos los vectores),
# los elementos de la columna 1, ósea la segunda columna [2 5]


[2 5]


7. Si x es un array x + 10 me dará un nuevo array en donde a cada elemento de x se le suma 10 porque NumPy trabaja los arreglos por bloques

In [10]:
b=np.array([[1, 2, 3],
            [4, 5, 6]]) #2x3

print(b+10) # Me dará un nuevo array en donde cada elemento
# de b será sumado con 10 respecto al original



[[11 12 13]
 [14 15 16]]


8. En M + v NumPy repite elementos automaticamente para poder operar una matriz y un vector.

9. La normalización al rango [0,1], es transformar los datos originales tal que el valor más pequeño sea cero y el más grande 1, y el resto proporcionalmente en medio respecto al original.

$$x_{norm} = \frac{x - x_{min}}{x_{max} - x_{min}}$$

Sirve para escalar a las variables de un problema dentro del mismo rango, lo que hace más eficiente los algoritmos al trabajar en el rango entre [0,1]. Ejemplo en código utilizando los conceptos previos

In [11]:
import numpy as np
x = np.array([10, 20, 30, 40, 50])
x_norm = (x - x.min()) / (x.max() - x.min()) # operaciones entre arreglos (bloques)
print(x_norm)

[0.   0.25 0.5  0.75 1.  ]


10. Por que las operaciones de NumPy utilizan a los arreglos a los que se les puede operar en bloque, en cambio un ciclo largo me utiliza más esfuerzo computacional y más líneas de código. Por lo tanto en casos donde se permita es conveniente usar operaciones de arreglos en numpy en vez de ciclos dado que es más eficiente.

In [12]:
b=np.array([[0],[1]]) # 2 filas, 1 columna
print(b.shape)

(2, 1)
